# Generated by Django 3.2.6 on 2021-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'Usd'), ('jpy', 'Jpy'), ('bgn', 'Bgn'), ('czk', 'Czk'), ('dkk', 'Dkk'), ('eek', 'Eek'), ('gbp', 'Gbp'), ('huf', 'Huf'), ('pln', 'Pln'), ('ron', 'Ron'), ('sek', 'Sek'), ('chf', 'Chf'), ('isk', 'Isk'), ('nok', 'Nok'), ('hrk', 'Hrk'), ('rub', 'Rub'), ('try', 'Try'), ('aud', 'Aud'), ('brl', 'Brl'), ('cad', 'Cad'), ('cny', 'Cny'), ('hkd', 'Hkd'), ('idr', 'Idr'), ('inr', 'Inr'), ('krw', 'Krw'), ('mxn', 'Mxn'), ('myr', 'Myr'), ('nzd', 'Nzd'), ('php', 'Php'), ('sgd', 'Sgd'), ('thb', 'Thb'), ('zar', 'Zar')], max_length=3)),
                ('value', models.DecimalField(decimal_places=5, max_digits=12)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['currency', 'date'],
            },
        ),
    ]
